name: Manually trigger an Azure Machine Learning job

on: [ pull_request ]

jobs:
  train-model:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in with Azure
        uses: azure/login@v1
        with:
          creds: '${{ secrets.AZURE_CREDENTIALS }}'

      - name: Trigger Azure Machine Learning job
        run: |
          az ml job create --file job.yml