name: Train model on production data

on: [ pull_request ]

jobs:
  train-model:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in with Azure
        uses: azure/login@v1
        with:
          creds: '${{ secrets.AZURE_CREDENTIALS }}'

      - name: Install Azure ML extension
        run: az extension add --name ml

      - name: Trigger Azure Machine Learning job
        run: |
          az ml job create --file job.yml --resource-group ${{ secrets.AZURE_RG }} --workspace-name ${{ secrets.AZURE_WS }}